"""empty message

Revision ID: 6de20f9f1d1b
Revises: cc11e0dbe96e
Create Date: 2025-03-13 14:04:47.539032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de20f9f1d1b'
down_revision: Union[str, None] = 'cc11e0dbe96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
