"""empty message

Revision ID: efdcad04ea85
Revises: 220a4e491b4f
Create Date: 2025-03-13 13:21:23.799003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdcad04ea85'
down_revision: Union[str, None] = '220a4e491b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.drop_constraint('courses_author_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'author_id')
    op.drop_constraint('refresh_token_token_key', 'refresh_token', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('refresh_token_token_key', 'refresh_token', ['token'])
    op.add_column('courses', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('courses_author_id_fkey', 'courses', 'user_profiles', ['author_id'], ['id'])
    op.drop_table('course_user')
    # ### end Alembic commands ###
